# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0009_auto_20171009_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
