# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-11 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_experience_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienceimage',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='experienceimage',
            name='image',
            field=models.ImageField(upload_to='experiences/'),
        ),
    ]
