version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=auctionrooms
    ports:
      - "5432:5432"

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
      - mailhog
      - redis
    environment:
      - POSTGRES_USER=auctionrooms
      - USE_DOCKER=yes
      - DATABASE_URL=postgis://auctionrooms@postgres/auctionrooms
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - redis
      - postgres
      - mailhog

  redis:
    build:
      context: .
      dockerfile: ./compose/redis/Dockerfile
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"

