# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-17 13:40
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.gis.geos import Point


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_load_intial_data'),
        ('auctions', '0002_auto_20170817_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='coords',
            field=django.contrib.gis.db.models.fields.PointField(default=Point(0, 0), srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency'),
        ),
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auction',
            name='pax_adults',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='auction',
            name='pax_children',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auction',
            name='terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auction',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
