# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-18 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionexclusion_auctionimage_auctioninclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionimage',
            name='auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='auctions.Auction'),
            preserve_default=False,
        ),
    ]
