# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auction_status_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='status',
        ),
    ]
