# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_favouriteauction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavouriteAuction',
            new_name='Favourite',
        ),
    ]
