# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 17:52
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20171019_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='uuid',
            field=django_extensions.db.fields.ShortUUIDField(blank=True, editable=False),
        ),
    ]
