# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_log', '0004_auto_20171023_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='type',
            field=models.IntegerField(choices=[(1, 'A new experience was created'), (2, 'A new auction was created'), (3, 'A bid was placed on an auction'), (4, 'Auction finished'), (5, 'User placed a bid on an auction'), (6, 'User submitted the winning bid on an auction'), (7, "User submitted the highest bid but didn't win the auction")]),
        ),
    ]
