# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-29 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctionimage_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
