# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 14:29
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auction_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='check_in',
            field=models.DateTimeField(help_text='The date and time the experience starts'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='check_out',
            field=models.DateTimeField(help_text='The date and time the experience ends'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='coords',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Location coordinates of the experience', srid=4326),
        ),
        migrations.AlterField(
            model_name='auction',
            name='currency',
            field=models.ForeignKey(default=1, help_text='The date and time the experience starts', on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.TextField(help_text='Description of the experience being auctioned'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(help_text='The date and time the auction finishes'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='experience',
            field=models.ForeignKey(help_text='The experience this auction was created from', on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='experiences.Experience'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='featured',
            field=models.BooleanField(default=False, help_text='Set to true to show this auction in the featured section on the homepage'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='location',
            field=models.CharField(help_text='Location name of the experience', max_length=255),
        ),
        migrations.AlterField(
            model_name='auction',
            name='pax_adults',
            field=models.PositiveSmallIntegerField(default=2, help_text='Number of adults accepted as part of the experience'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='pax_children',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of children accepted as part of the experience'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='reserve_price',
            field=models.DecimalField(decimal_places=2, help_text='The minimum price that will be accpeted to win this auction', max_digits=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='search_appearance_count',
            field=models.PositiveIntegerField(default=0, help_text='The number of times this auction has appeared in search results or on the homepage'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, help_text='The initial price for the auction when it goes live', max_digits=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='terms',
            field=models.TextField(blank=True, help_text='Terms and conditions for the auction/experience', null=True),
        ),
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.CharField(help_text='Title of the experience being auctioned', max_length=255),
        ),
        migrations.AlterField(
            model_name='auction',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='The number of times auction details have been viewed'),
        ),
    ]
