# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_auction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.IntegerField(choices=[(1, 'Live'), (2, 'Finished Sold'), (3, 'Finished Unsold')], default=1),
        ),
    ]
