# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20171013_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='auctions.Auction'),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together=set([('auction', 'price')]),
        ),
    ]
