# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_favourite_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='new_listing_sent',
            field=models.BooleanField(default=False),
        ),
    ]
