# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 09:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auctions', '0017_favourite_new_listing_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favourite',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together=set([('auction', 'user')]),
        ),
    ]
