# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('symbol', models.CharField(max_length=3)),
                ('html_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
