# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_auction_help',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_dashboard_welcome',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='show_experience_help',
            field=models.BooleanField(default=True),
        ),
    ]
