# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 20:34
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('coords', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('terms', models.TextField(blank=True, null=True)),
                ('pax_adults', models.PositiveSmallIntegerField(default=2)),
                ('pax_children', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='ExperienceExclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exclusions', to='experiences.Experience')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='experiemces/')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='experiences.Experience')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceInclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='experiences.Experience')),
            ],
        ),
    ]
