# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 06:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_experience_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='currencies.Currency'),
        ),
    ]
