# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-16 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0007_auto_20170911_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='experience',
            name='banner_image',
        ),
    ]
