# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 06:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiences', '0002_experience_currency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('deleted', models.BooleanField(default=False)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reserve_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('end_date', models.DateTimeField()),
                ('view_count', models.PositiveIntegerField()),
                ('search_appearance_count', models.PositiveIntegerField()),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='experiences.Experience')),
            ],
            options={
                'abstract': False,
                'get_latest_by': 'created',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('deleted', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.Auction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-price',),
            },
        ),
    ]
