# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-24 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auction_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
