# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-20 18:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'get_latest_by': 'created'},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 20, 18, 9, 32, 9999), verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
