# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-19 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, b'Guest'), (2, b'Provider')], default=1),
            preserve_default=False,
        ),
    ]
